### ISSUE TITLE
Getting deprecated API till v.125

### ISSUE THREAD

**Issue by ankit-arora-369** [gkarthiks/argo-apid-helper#11]
Hi

Using apid-helper, I am getting getting the list of deprecated APIs till v1.25 and not getting for v1.26 which is already released by k8s.
Using kubent we are getting the list for v1.26 as well.
Can you please look into this and fix it?

Thanks

**Comment by ankit-arora-369** [comment]
Sure, thanks.

**Comment by ankit-arora-369** [comment]
Hey man, any update here?

**Comment by ankit-arora-369** [comment]
Hi

Any update?

Thanks

**Comment by gkarthiks** [comment]
Hi @ankit-arora-369 i am working on it. For some reason quay.io build node is not unpacking the build package. Working on it and apologies for the delay.

**Comment by gkarthiks** [comment]
Hi @ankit-arora-369 the https://github.com/gkarthiks/argo-apid-helper/releases/tag/v0.2.2 app release with https://github.com/gkarthiks/argo-apid-helper/releases/tag/helm-v0.1.3 helm chart should able to report you the latest deprecation.

Kindly validate and le me know.

**Comment by ankit-arora-369** [comment]
Thanks a lot! @gkarthiks

**Comment by ankit-arora-369** [comment]
@gkarthiks It's still printing the deprecated APIs till 1.25.

I tried all of your images and also created the image from the Dockerfile but still it's printing till 1.25.

Can you please look into this?

**Comment by ankit-arora-369** [comment]
@gkarthiks Any possibility to fix this?

**Comment by gkarthiks** [comment]
Hi, sure. Give me about 2 days. Will definitely look into this.

**Comment by gkarthiks** [comment]
hi @ankit-arora-369 have updated the app. Use the v0.2.3 version with the 0.1.4 chart. That should get you the results. 

Thanks for the continued support. Consider leaving a star for this repo.

**Comment by ankit-arora-369** [comment]
@gkarthiks It's still not listing the deprecated APIs after 1.25. I wanted to write the blog on this but it's still not working.

No worries, I will try to patch it myself.

Thanks for the help man.

**Comment by gkarthiks** [comment]
@ankit-arora-369 I am using this commit https://github.com/doitintl/kube-no-trouble/tree/e506263e684a9d655d9f552de52cb225522af390 which is supposed to list those deprecations, not sure what's happening there. 

But if you could do a PR, I would really appreciate it.
